name: Auto-Version Agent

on:
  push:
    branches:
      - main
    paths:
      - 'linux/agent.sh'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Sjekk ut kode
        uses: actions/checkout@v4

      - name: Injisere versjon og commit-hash
        run: |
          SHA_SHORT=$(git rev-parse --short HEAD)
          DATE_VERSION=$(date +'%Y.%m.%d')
          FULL_VERSION="${DATE_VERSION}-${SHA_SHORT}"
          
          echo "Setter versjon til: $FULL_VERSION"
          
          # Endrer filen kun i det midlertidige bygget på GitHub-serveren
          sed -i "s/AGENT_VERSION=\"DEV-BUILD\"/AGENT_VERSION=\"$FULL_VERSION\"/g" linux/agent.sh
          sed -i "s/COMMIT_HASH=\"local\"/COMMIT_HASH=\"$SHA_SHORT\"/g" linux/agent.sh

      - name: Push ferdig skript til release-branch (uten å forstyrre main)
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: release # Roboten dytter den ferdige filen hit!
          folder: linux # Tar innholdet i linux-mappa og legger på rota av release-branchen
          single-commit: true
